local M = {}

function M.get()
	return {
		ColorColumn = { bg = C.surface0 },
		Conceal = { fg = C.overlay1 },
		Cursor = { fg = C.base, bg = C.text },
		lCursor = { fg = C.base, bg = C.text },
		CursorIM = { fg = C.base, bg = C.text },
		CursorColumn = { bg = C.mantle },
		CursorLine = { bg = O.transparent_background and C.none or C.mantle },
		Directory = { fg = C.blue },
		EndOfBuffer = { fg = O.show_end_of_buffer and C.surface1 or C.base },
		ErrorMsg = { fg = C.error, style = { "bold" } },
		VertSplit = { fg = O.transparent_background and C.surface1 or C.surface0 },
		Folded = { fg = C.blue, bg = O.transparent_background and C.none or C.surface1 },
		FoldColumn = { fg = C.overlay0 },
		SignColumn = { fg = C.surface1 },
		SignColumnSB = { bg = C.mantle, fg = C.surface1 },
		Substitute = { bg = C.surface1, fg = C.pink },
		LineNr = { fg = "#4c4c55" },
		CursorLineNr = { fg = "#9aa5ce" },
		MatchParen = { fg = C.peach, bg = U.darken(C.surface1, 0.70, C.base), style = { "bold" } },
		ModeMsg = { fg = C.text, style = { "bold" } },
		MsgSeparator = { link = "WinSeparator" },
		MoreMsg = { fg = C.blue },
		NonText = { fg = C.overlay0 },
		Normal = { fg = C.text, bg = O.transparent_background and C.none or C.base },
		NormalNC = {
			fg = C.text,
			bg = (O.transparent_background and O.dim_inactive.enabled and C.dim)
				or (O.dim_inactive.enabled and C.dim)
				or (O.transparent_background and C.none)
				or C.base,
		},
		NormalSB = { fg = C.text, bg = C.mantle },
		NormalFloat = { fg = C.text, bg = (O.float.transparent and vim.o.winblend == 0) and C.none or C.mantle },
		FloatBorder = { fg = C.blue, bg = (O.float.transparent and vim.o.winblend == 0) and C.none or C.mantle },
		FloatTitle = { fg = C.subtext0, bg = (O.float.transparent and vim.o.winblend == 0) and C.none or C.mantle },
		FloatShadow = { bg = C.surface0, blend = 80 },
		FloatShadowThrough = { bg = C.surface0, blend = 100 },
		Pmenu = {
			bg = (O.transparent_background and vim.o.pumblend == 0) and C.none or C.mantle,
			fg = C.overlay2,
		},
		PmenuSel = { bg = C.surface0, style = { "bold" } },
		PmenuMatch = { fg = C.text, style = { "bold" } },
		PmenuMatchSel = { style = { "bold" } },
		PmenuSbar = { bg = C.surface0 },
		PmenuThumb = { bg = C.overlay0 },
		PmenuExtra = { fg = C.overlay0 },
		PmenuExtraSel = {
			bg = C.surface0,
			fg = C.overlay0,
			style = { "bold" },
		},
		Question = { fg = C.blue },
		QuickFixLine = { bg = U.darken(C.surface1, 0.70, C.base), style = { "bold" } },
		Search = { bg = "#d8616b40", fg = C.text },
		IncSearch = { bg = "#d8616b30", fg = C.mantle },
		CurSearch = { link = "IncSearch" },
		SpecialKey = { link = "NonText" },
		SpellBad = { sp = C.error, style = { "undercurl" } },
		SpellCap = { sp = C.warning, style = { "undercurl" } },
		SpellLocal = { sp = C.info, style = { "undercurl" } },
		SpellRare = { sp = C.ok, style = { "undercurl" } },
		StatusLine = { fg = C.text, bg = O.transparent_background and C.none or C.base },
		StatusLineNC = { fg = C.surface1, bg = O.transparent_background and C.none or C.base },
		TabLine = { bg = C.base, fg = "#565f89" },
		TabLineFill = { bg = O.transparent_background and C.none or C.base },
		TabLineSel = { bg = C.mantle, fg = C.text },
		TermCursor = { fg = C.base, bg = C.text },
		TermCursorNC = { fg = C.base, bg = C.overlay2 },
		Title = { fg = C.blue, style = { "bold" } },
		Visual = { bg = C.surface1, style = { "bold" } },
		VisualNOS = { bg = C.surface1, style = { "bold" } },
		WarningMsg = { fg = C.warning },
		Whitespace = { fg = C.surface1 },
		WildMenu = { bg = C.overlay0 },
		WinBar = { fg = C.text },
		WinBarNC = { link = "WinBar" },
		WinSeparator = { fg = O.transparent_background and C.surface1 or C.surface0 },
	}
end

return M
