local M = {}

function M.get()
	return {
		["@lsp.type.comment"] = { link = "@comment" },
		["@lsp.type.enum"] = { link = "@type" },
		["@lsp.type.enumMember"] = { link = "@constant" },
		["@lsp.type.interface"] = { link = "@type" },
		["@lsp.type.keyword"] = { link = "@keyword" },
		["@lsp.type.macro"] = { link = "@macro" },
		["@lsp.type.method"] = { link = "@function.method" },
		["@lsp.type.namespace"] = { link = "@module" },
		["@lsp.type.parameter"] = { link = "@variable.parameter" },
		["@lsp.type.property"] = { link = "@property" },
		["@lsp.type.struct"] = { link = "@structure" },
		["@lsp.type.typeAlias"] = { link = "@type.definition" },
		["@lsp.type.typeParameter"] = { link = "@type.parameter" },
		["@lsp.type.variable"] = { link = "@variable" },
		["@lsp.mod.readonly"] = { style = { "nocombine" } },

		["@lsp.type.variable.typescript"] = { link = "@variable.typescript" },
		["@lsp.type.keyword.typescript"] = { link = "@keyword.typescript" },
		["@lsp.type.method.typescript"] = { link = "@function.method.typescript" },
		["@lsp.type.parameter.typescript"] = { link = "@variable.parameter.typescript" },
		["@lsp.type.property.typescript"] = { link = "@property.typescript" },
		["@lsp.type.typeAlias.typescript"] = { link = "@type.typescript" },
		["@lsp.typemod.variable.readonly.typescript"] = { style = { "nocombine" } },

		["@lsp.type.variable.rust"] = { link = "@variable.rust" },
		["@lsp.type.keyword.rust"] = { link = "@keyword.rust" },
		["@lsp.type.method.rust"] = { link = "@function.method.rust" },
		["@lsp.type.parameter.rust"] = { link = "@variable.parameter.rust" },
		["@lsp.type.property.rust"] = { link = "@property.rust" },
		["@lsp.type.macro.rust"] = { link = "@macro.rust" },
		["@lsp.typemod.variable.defaultLibrary.rust"] = { link = "@variable.builtin.rust" },
		["@lsp.typemod.variable.readonly.rust"] = { style = { "nocombine" } },
		["@lsp.typemod.class.defaultLibrary"] = { link = "@type.builtin" },
		["@lsp.typemod.enum.defaultLibrary"] = { link = "@type.builtin" },
		["@lsp.typemod.enumMember.defaultLibrary"] = { link = "@constant.builtin" },
		["@lsp.typemod.function.defaultLibrary"] = { link = "@function.builtin" },
		["@lsp.typemod.method.defaultLibrary"] = { link = "@function.builtin" },
		["@lsp.typemod.operator.defaultLibrary"] = { link = "@operator" },
		["@lsp.typemod.parameter.defaultLibrary"] = { link = "@variable.builtin" },
		["@lsp.typemod.property.defaultLibrary"] = { link = "@variable.builtin" },
		["@lsp.typemod.struct.defaultLibrary"] = { link = "@type.builtin" },
		["@lsp.typemod.struct.library"] = { link = "@type.builtin" },
		["@lsp.typemod.struct.macro"] = { link = "@type.builtin" },
		["@lsp.typemod.struct.procMacro"] = { link = "@type.builtin" },
		["@lsp.typemod.struct.public"] = { link = "@type" },
		["@lsp.typemod.variable.defaultLibrary"] = { link = "@variable.builtin" },
		["@lsp.typemod.function.unused"] = { fg = C.unused },
		["@lsp.typemod.variable.unused"] = { fg = C.unused },
		["@lsp.typemod.method.unused"] = { fg = C.unused },
		["@lsp.typemod.parameter.unused"] = { fg = C.unused },
		["@lsp.typemod.property.unused"] = { fg = C.unused },
		["@lsp.typemod.class.unused"] = { fg = C.unused },
		["@lsp.typemod.struct.unused"] = { fg = C.unused },
		["@lsp.typemod.enum.unused"] = { fg = C.unused },
		["@lsp.typemod.enumMember.unused"] = { fg = C.unused },
		["@lsp.typemod.interface.unused"] = { fg = C.unused },
		["@lsp.typemod.namespace.unused"] = { fg = C.unused },
		["@lsp.typemod.typeAlias.unused"] = { fg = C.unused },
		["@lsp.typemod.typeParameter.unused"] = { fg = C.unused },
		["@lsp.mod.unused"] = { fg = C.unused },
		["@lsp.mod.deprecated"] = { fg = C.unused },
	}
end

return M
