local M = {}

function M.get()
	return {
		Comment = { fg = "#4c4c55", style = O.styles.comments or { "italic" } },
		SpecialComment = { link = "Special" },
		Constant = { fg = C.orange },
		String = { fg = C.green, style = O.styles.strings or {} },
		Character = { fg = C.peach, style = { "bold" } },
		Number = { fg = C.orange, style = O.styles.numbers or {} },
		Float = { link = "Number" },
		Boolean = { fg = C.orange, style = O.styles.booleans or {} },
		Identifier = { fg = C.text, style = O.styles.variables or {} },
		Function = { fg = C.blue, style = O.styles.functions or {} },
		Statement = { fg = C.mauve },
		Conditional = { fg = C.mauve, style = O.styles.conditionals or {} },
		Repeat = { fg = C.mauve, style = O.styles.loops or {} },
		Label = { fg = C.orange },
		Operator = { fg = C.text, style = O.styles.operators or {} },
		Keyword = { fg = C.mauve, style = O.styles.keywords or {} },
		Exception = { fg = C.mauve, style = O.styles.keywords or {} },

		PreProc = { fg = C.error },
		Include = { fg = C.blue, style = O.styles.keywords or { "italic" } },
		Define = { link = "PreProc" },
		Macro = { fg = C.error },
		PreCondit = { link = "PreProc" },

		StorageClass = { fg = C.mauve },
		Structure = { fg = C.orange },
		Special = { fg = C.pink },
		typescriptDecorator = { fg = C.yellow },
		Type = { fg = C.peach, style = O.styles.types or {} },
		Typedef = { link = "Type" },
		SpecialChar = { link = "Special" },
		Tag = { fg = C.peach },
		Delimiter = { fg = "#9aa5ce" },
		Debug = { link = "Special" },

		Underlined = { style = { "underline" } },
		Bold = { style = { "bold" } },
		Italic = { style = { "italic" } },

		Error = { fg = C.error },
		Todo = { bg = C.pink, fg = C.base, style = { "bold" } },
		qfLineNr = { fg = C.peach },
		qfFileName = { fg = C.blue },
		htmlH1 = { fg = C.pink, style = { "bold" } },
		htmlH2 = { fg = C.blue, style = { "bold" } },
		mkdCodeDelimiter = { bg = C.base, fg = C.text },
		mkdCodeStart = { fg = C.pink, style = { "bold" } },
		mkdCodeEnd = { fg = C.pink, style = { "bold" } },

		debugPC = { bg = O.transparent_background and C.none or C.mantle },
		debugBreakpoint = { bg = C.base, fg = C.overlay0 },

		illuminatedWord = { bg = C.surface1 },
		illuminatedCurWord = { bg = C.surface1 },

		Added = { fg = C.green },
		Changed = { fg = C.peach },
		diffAdded = { fg = C.green },
		diffRemoved = { fg = C.error },
		diffChanged = { fg = C.peach },
		diffOldFile = { fg = C.peach },
		diffNewFile = { fg = C.orange },
		diffFile = { fg = C.blue },
		diffLine = { fg = C.overlay0 },
		diffIndexLine = { fg = C.sky },
		DiffAdd = { bg = U.darken(C.green, 0.90, C.base) },
		DiffChange = { bg = U.darken(C.blue, 0.70, C.base) },
		DiffDelete = { bg = U.darken(C.error, 0.90, C.base) },
		DiffText = { bg = U.darken(C.blue, 0.50, C.base) },

		healthError = { fg = C.error },
		healthSuccess = { fg = C.sky },
		healthWarning = { fg = C.warning },

		GlyphPalette1 = { fg = C.error },
		GlyphPalette2 = { fg = C.sky },
		GlyphPalette3 = { fg = C.peach },
		GlyphPalette4 = { fg = C.blue },
		GlyphPalette6 = { fg = C.sky },
		GlyphPalette7 = { fg = C.text },
		GlyphPalette9 = { fg = C.error },

		rainbow1 = { fg = C.error },
		rainbow2 = { fg = C.peach },
		rainbow3 = { fg = C.peach },
		rainbow4 = { fg = C.green },
		rainbow5 = { fg = C.blue },
		rainbow6 = { fg = C.lavender },

		csvCol0 = { fg = C.error },
		csvCol1 = { fg = C.peach },
		csvCol2 = { fg = C.peach },
		csvCol3 = { fg = C.green },
		csvCol4 = { fg = C.blue },
		csvCol5 = { fg = C.blue },
		csvCol6 = { fg = C.lavender },
		csvCol7 = { fg = C.mauve },
		csvCol8 = { fg = C.pink },

		markdownHeadingDelimiter = { fg = C.peach, style = { "bold" } },
		markdownCode = { fg = C.pink },
		markdownCodeBlock = { fg = C.pink },
		markdownLinkText = { fg = C.blue, style = { "underline" } },
		markdownH1 = { link = "rainbow1" },
		markdownH2 = { link = "rainbow2" },
		markdownH3 = { link = "rainbow3" },
		markdownH4 = { link = "rainbow4" },
		markdownH5 = { link = "rainbow5" },
		markdownH6 = { link = "rainbow6" },
	}
end

return M
